#!/bin/bash

command="$1"

if [ "$command" = "remove" ]; then
    umount /media/ipad
    exit
fi

ifuse /media/ipad

pics=0

if [ -d "/media/ipad/DCIM/100APPLE" ]; then
    cd /media/ipad/DCIM/100APPLE
    # You'd normally just use rsync or something here, but we do
    # it manually here because we post-process the file names for
    # this particular application.
    for pic in IMG*; do
	to="/home/larsi/pics/ipad"
	if [ ! -f "$to/$pic" ]; then
	    cp -av "$pic" "$to/$pic"
	    chown larsi.users "$to/$pic"
	    pics=$(($pics + 1))
	    # In addition to syncing to the main directory, also rename
	    # and put these files into the current directory for the
	    # film I'm watching.
	    if echo "$pic" | grep PNG > /dev/null; then
		shot=`echo "$pic" | sed 's/IMG_/shot/' | sed 's/PNG/png/'`
		if [ ! -f "/home/larsi/.movie-current/$shot" ]; then
		    ln "$to/$pic" "/home/larsi/.movie-current/$shot"
		fi
	    fi
	fi
    done
fi

cd /
umount /media/ipad

if [ "$pics" = "1" ]; then
    message="picture"
else
    message="pictures"
fi

# Tell the user what happened.
DISPLAY=:0.0 XAUTHORITY=/home/larsi/.Xauthority notify-send "Ipad Picture Copier" "Copied $pics $message"
